name: itopya_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'
dependency_overrides:
  intl: ^0.19.0

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  google_fonts: 6.1.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  go_router: ^13.2.0
  preload_page_view: ^0.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  http: ^1.2.0
  carousel_slider: ^4.2.1
  grock: ^0.5.6
  flutter_bloc: ^8.1.5
  flex_color_scheme: ^7.3.1
  flutter_localization: ^0.2.0
  permission_handler: ^11.3.1
  dash_chat_2: ^0.0.20
  flutter_gemini: ^2.0.3
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.0
  image_cropper: ^7.0.3
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
flutter_native_splash:
  color: "#000000"
  fullscreen: true
  image: assets/images/splash.png
  icon_background_color: "#000000"
  android: true
  ios: true
  android_12:
    color: "#000000"
    image: assets/images/splash.png 
    icon_background_color: "#000000"
    fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/icons/